### ISSUE TITLE
BuildScript\Requirments

### ISSUE THREAD

**Issue by CoolHandSquid** [secw01f/webrecon#1]
Your tool appears to be a neat go-to, but the amount of building needed to use it is excessive. Would you consider making a build script so it would function on a 2020 Kali box? Feel free to message me on coolhandsquid@yahoo.com if you would like to collaborate.

**Comment by secw01f** [comment]
Hi @CoolHandSquid,

Thanks for your feedback! I apologize for the delayed response but I have added a quick setup script to the repository and updated the install instructions.

Let me know if you have any issues and I can make any changes that are needed and can reopen the issue.

Thanks!

**Comment by CoolHandSquid** [comment]
![Secwolf](https://user-images.githubusercontent.com/42553774/79753378-d4f16b80-82e3-11ea-9b6a-837aa0dd04d5.PNG)
Does not install properly on kali 2020.

**Comment by secw01f** [comment]
I pushed a new setup.sh script that I have confirmed works on Kali 2020.

Thanks for you patience!
